#define GRAPH_LENGTH 1300
#define GRAPH_HIGH 600

#define TRIP1_OUTER_MARGIN_X 20
#define TRIP1_OUTER_MARGIN_Y 0
#define TRIP1_X TRIP1_OUTER_MARGIN_X
#define TRIP1_Y TRIP1_OUTER_MARGIN_Y

#define FRAME_OUTER_MARGIN_X 20
#define FRAME_OUTER_MARGIN_Y 20

#define LEFT_TOP_X FRAME_OUTER_MARGIN_X
#define LEFT_TOP_Y FRAME_OUTER_MARGIN_Y

#define RIGHT_TOP_X GRAPH_LENGTH - FRAME_OUTER_MARGIN_X
#define RIGHT_TOP_Y FRAME_OUTER_MARGIN_Y

#define LEFT_BOTTOM_X FRAME_OUTER_MARGIN_X
#define LEFT_BOTTOM_Y GRAPH_HIGH - FRAME_OUTER_MARGIN_Y

#define RIGHT_BOTTOM_X GRAPH_LENGTH - FRAME_OUTER_MARGIN_X
#define RIGHT_BOTTOM_Y GRAPH_HIGH - FRAME_OUTER_MARGIN_Y

#define TRIP2_OUTER_MARGIN_X 20
#define TRIP2_OUTER_MARGIN_Y 10

#define TRIP2_INTER_MARGIN_Y 20

#define TRIP2_X LEFT_TOP_X + TRIP2_OUTER_MARGIN_X
#define TRIP2_Y LEFT_TOP_Y + TRIP2_OUTER_MARGIN_Y

#define VEHICLE_LEFT_BOTTOM_X LEFT_TOP_X + 5
#define VEHICLE_LEFT_BOTTOM_Y LEFT_TOP_Y + 500

#define VEHICLE_WHEEL_RADIUS 10
#define VEHICLE_WHEEL_DIAMETER VEHICLE_WHEEL_RADIUS * 2

#define ROAD_LENTTH GRAPH_LENGTH - FRAME_OUTER_MARGIN_X * 2
#define ROAD_HIGH 5

#define MOVE_INTER_TIME 20
#define MOVE_INTER_X 1
#define MOVE_INTER_Y 0